name: Process PDFs

on:
  schedule:
    - cron: '3 0 * * 1'  # Runs at 00:03 every Monday
  workflow_dispatch:

jobs:
  process-and-commit-pdfs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Environment
      run: sudo apt-get update && sudo apt-get install -y ghostscript wget

    - name: Download Original PDF
      run: |
        # Ensure date components do not have leading zeros for arithmetic or URL construction
        YEAR=$(date +%Y)
        MONTH=$(date +%m | sed 's/^0*//')  # Removes leading zeros
        DAY=$(date +%d | sed 's/^0*//')    # Removes leading zeros
        DATE=$(printf "%02d/%02d/%04d" $DAY $MONTH $YEAR)  # Formats date as DD/MM/YYYY
        URL="https://geowacht.be/wachtkaart.html?pharmacy=371201&date=${DATE}&language=NL"
        wget -O original_wachtkaart.pdf "${URL}"

    - name: Process PDFs
      run: |
        # Crop and include only the first page for maandag-donderdag.pdf
        gs -sDEVICE=pdfwrite -o maandag-donderdag.pdf \
           -c "[/CropBox [80 100 520 780] /PAGES pdfmark" \
           -f original_wachtkaart.pdf -dNOPAUSE -dBATCH -dSAFER \
           -dFirstPage=1 -dLastPage=1

        # Crop and include only the second page for vrijdag-zondag.pdf
        gs -sDEVICE=pdfwrite -o vrijdag-zondag.pdf \
           -c "[/CropBox [80 100 520 780] /PAGES pdfmark" \
           -f original_wachtkaart.pdf -dNOPAUSE -dBATCH -dSAFER \
           -dFirstPage=2 -dLastPage=2

    - name: Generate Commit Message
      run: |
        WEEK=$(date +%V)
        echo "name=Updated Geowacht schedules for week $WEEK" >> $GITHUB_ENV

    - name: Commit and Push PDFs
      uses: EndBug/add-and-commit@v7
      with:
        author_name: GeowachtBot
        author_email: geowachtbot@thibaultmol.link
        message: ${{ env.name }}
        add: 'maandag-donderdag.pdf vrijdag-zondag.pdf'
        push: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
