name: Process PDFs

on:
  schedule:
    - cron: '3 0 * * 1'  # Runs at 00:03 every Monday
  workflow_dispatch:

jobs:
  process-and-commit-pdfs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup Environment
      run: |
        sudo apt-get update
        sudo apt-get install -y ghostscript

    - name: Download Original PDF
      run: |
        TODAY=$(date +%d/%m/%Y)
        URL="https://geowacht.be/wachtkaart.html?pharmacy=371201&date=${TODAY}&language=NL"
        curl -o original_wachtkaart.pdf "${URL}"

    - name: Process PDFs
      run: |
        gs -o maandag-donderdag.pdf -sDEVICE=pdfwrite -c "[/CropBox [80 100 520 780] /PAGES pdfmark" -f original_wachtkaart.pdf
        gs -o vrijdag-zondag.pdf -sDEVICE=pdfwrite -c "[/CropBox [80 100 520 780] /PAGES pdfmark" -f original_wachtkaart.pdf

    - name: Generate Commit Message
      id: commit-message
      run: |
        YEAR=$(date +%Y)
        WEEK=$(date +%V)
        START_DATE=$(date -d "$YEAR-01-01 +$((WEEK-1)) weeks" +"%d/%m/%Y")
        END_DATE=$(date -d "$START_DATE +6 days" +"%d/%m/%Y")
        echo "::set-output name=message::Updated Geowacht schedules for week $WEEK of $YEAR ($START_DATE to $END_DATE)"

    - name: Commit and Push PDFs
      uses: EndBug/add-and-commit@v7
      with:
        author_name: GeowachtBot
        author_email: geowachtbot@thibaultmol.link
        message: ${{ steps.commit-message.outputs.message }}
        add: 'maandag-donderdag.pdf vrijdag-zondag.pdf'
        push: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
