name: Process PDFs

on:
  schedule:
    - cron: '3 0 * * 1'  # Runs at 00:03 every Monday
  workflow_dispatch:

jobs:
  process-and-commit-pdfs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Environment
        run: |
          sudo apt-get update
          sudo apt-get install -y ghostscript wget pdf2svg

      - name: Download Original PDF
        run: |
          YEAR=$(date +%Y)
          MONTH=$(date +%m | sed 's/^0*//')
          DAY=$(date +%d | sed 's/^0*//')
          DATE=$(printf "%02d/%02d/%04d" $DAY $MONTH $YEAR)
          URL="https://geowacht.be/wachtkaart.html?pharmacy=371201&date=${DATE}&language=NL"
          wget -O original_wachtkaart.pdf "${URL}"

      - name: Process PDFs
        run: |
          # Crop and split the PDF (Commented out for SVG conversion)
          gs -sDEVICE=pdfwrite -dNOPAUSE -dBATCH -dSAFER \
             -dFirstPage=1 -dLastPage=1 \
             -sOutputFile=docs/maandag-donderdag.pdf \
             -c "[/CropBox [80 100 520 780] /PAGES pdfmark" -f original_wachtkaart.pdf

          gs -sDEVICE=pdfwrite -dNOPAUSE -dBATCH -dSAFER \
             -dFirstPage=2 -dLastPage=2 \
             -sOutputFile=docs/vrijdag-zondag.pdf \
             -c "[/CropBox [80 100 520 780] /PAGES pdfmark" -f original_wachtkaart.pdf

          # Convert cropped PDFs to SVG (New steps)
          pdf2svg docs/maandag-donderdag.pdf docs/maandag-donderdag.svg
          pdf2svg docs/vrijdag-zondag.pdf docs/vrijdag-zondag.svg

      - name: Generate Commit Message
        run: |
          WEEK=$(date +%V)
          echo "name=Updated Geowacht schedules for week $WEEK" >> $GITHUB_ENV

      - name: Commit and Push Files
        uses: EndBug/add-and-commit@v7
        with:
          author_name: GeowachtBot
          author_email: geowachtbot@thibaultmol.link
          message: ${{ env.name }}
          # Adjust to commit SVG files (and keep PDF lines commented)
          # add: 'docs/maandag-donderdag.pdf docs/vrijdag-zondag.pdf'
          add: 'docs/maandag-donderdag.svg docs/vrijdag-zondag.svg'
          push: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
